language: php

php:
  - 5.6

services:
  - rabbitmq # will start rabbitmq-server
#  - mongodb
#  - redis-server
#  - elasticsearch

cache:
    directories:
        - ~/.composer/cache

git:
  submodules: false

env:
  - BASE_URL="http://127.0.0.1/" API_BASE_URL="http://127.0.0.2/app_test.php" NODE_ENV=travis NODE_CONFIG_DIR=./gameserver/config

before_script:
# Prepare Webserver
 - sudo apt-get install apache2 libapache2-mod-fastcgi

# Enable php-fpm
 - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
 - sudo a2enmod rewrite actions fastcgi alias
 - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

# Configure apache virtual hosts
 - sudo cp -f app/config/travis-ci-apache-api.conf /etc/apache2/sites-available/api.conf
 - sudo cp -f app/config/travis-ci-apache-client.conf /etc/apache2/sites-available/client.conf
 - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/api.conf
 - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/client.conf
 - sudo a2ensite api.conf client.conf
 - sudo service apache2 restart

# Set the GitHub OAuth token to make use of the 6000 per hour rate limit
# - cp .travis-composer-config.json ~/.composer/config.json

# Symfony specific
 - cp app/config/parameters.yml.travis app/config/parameters.yml
 - cp app/config/deploy.rb.dist app/config/deploy.rb
 - composer install --no-progress --prefer-dist
 - php app/console doctrine:database:create --env=test
 - php app/console doctrine:schema:create --env=test
 - mkdir -p app/cache app/logs
 - chmod -R 777 /tmp/cache /tmp/logs app/cache app/logs

# Assets dependencies
 - npm install
 - npm install -g bower protractor cucumber karma-cli
 - bower install

# JS specific
 - cp client/config/main.json.travis client/config/main.json

# Protractor
 - sudo apt-get update
 - sudo apt-get install chromium-browser
 - webdriver-manager update --standalone
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99.0 -ac -screen 0 1280x1024x24"

# RabbitMQ
 - sudo chmod +x bin/prepare-rabbit.sh
 - sudo ./bin/prepare-rabbit.sh

script:
    - gulp
    - php app/console doctrine:fixtures:load -n --env=test
    - php app/console security:check
    - php bin/phpspec run
    - php bin/behat
    - protractor protractor.conf.js

after_success:
    - openssl aes-256-cbc -K $encrypted_168c5169b1c4_key -iv $encrypted_168c5169b1c4_iv -in app/config/id_rsa.enc -out app/config/id_rsa -d
    - gem install capifony
#    - if [ $TRAVIS_BRANCH == 'master' ]; then
#        cap deploy;
#      fi

after_script:
  - php -v
  - tail /tmp/logs/test.log
  - sudo cat /var/log/apache2/error.log
