users:
    type:     rest
    resource: AppBundle\Controller\UsersController

emails:
    type:     rest
    resource: AppBundle\Controller\EmailsController

teams:
    type:     rest
    resource: AppBundle\Controller\TeamsController

gameobjecttypes:
    type:     rest
    resource: AppBundle\Controller\GameObjectTypesController

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
   path: /login_check
